name: Android CD Pipeline

# Grant write permission to create release through github action
permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  validate:
    name: Validate Branch
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on production branch
        if: endsWith(github.event.base_ref, 'master') == false
        run: exit -1

  build:
    needs: validate
    name: Build App Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        id: buildReleaseApk
        run: ./gradlew assembleRelease --stacktrace

      - name: Build Release AAB
        id: buildReleaseAab
        run: ./gradlew bundleRelease --stacktrace
      

      - name: Upload Release Build
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab      
